-- Table: retirement_staging.lifestyle_deposits

-- DROP TABLE IF EXISTS retirement_staging.lifestyle_deposits;

CREATE TABLE IF NOT EXISTS retirement_staging.lifestyle_deposits
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    lifestyle_type character varying(255) COLLATE pg_catalog."default",
    monthly_deposit numeric(38,2),
    CONSTRAINT lifestyle_deposits_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS retirement_staging.lifestyle_deposits
    OWNER to postgresuser;

	INSERT INTO retirement_staging.lifestyle_deposits (lifestyle_type, monthly_deposit) VALUES
('simple', 1000.00),
('fancy', 3000.00);

select * from retirement_staging.lifestyle_deposits

UPDATE retirement_staging.lifestyle_deposits
SET monthly_deposit = 1000.00
WHERE lifestyle_type = 'simple';

