# src/main/resources/application.yaml

server:
  port: 8080 # Default server port

spring:
  profiles:
    active: dev

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    groups:
      enabled: true

datasource:
initialization-mode: always
continue-on-error: true
jpa:
defer-datasource-initialization: true