
# src/main/resources/application-dev.yaml

# --- Development Profile Configuration ---
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: postgresuser
    password: postgrespassword
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql  # Explicitly specify the database type
    database-platform: org.hibernate.dialect.PostgreSQLDialect  # Explicitly set the dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: retirement_staging
        format_sql: true

  redis:
    host: localhost
    port: 6379

# springdoc/swagger configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
  groups:
    enabled: true
  paths-to-match: /retirement-plans/**

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springdoc: DEBUG
    org.springframework.boot.web.servlet.error: DEBUG
    org.hibernate: ERROR