# src/main/resources/application-dev.yaml

# --- Development Profile Configuration ---
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: postgresuser
    password: postgrespassword
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql  # Explicitly specify the database type
    database-platform: org.hibernate.dialect.PostgreSQLDialect  # Explicitly set the dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: retirement_staging
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true

  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

logging:
  level:
    org.springframework.web: DEBUG # Example: Set web logging to DEBUG in dev
    org.hibernate.SQL: DEBUG  # Added to help with SQL logging
    org.hibernate.type.descriptor.sql: TRACE  # Shows parameter binding
    # Add other package specific logging levels here